name: "Update Flake Inputs"

on:
  schedule:
    - cron: '0 0 * * 0' 
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    
    - name: Update Flake Inputs
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        nix flake update
        
        if [[ -n $(git status --porcelain) ]]; then
          git add flake.lock
          git commit -m "chore: update flake inputs"
          git push
        else
          echo "No updates found"
        fi